In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder



pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


In [2]:
data = pd.read_csv('DDHealth_v3.csv')

In [3]:
data.head()

ID      pond  ENTREV   DURACION                 CCAA        PROV  \
0   3  0.801296     773  15.066667  Comunidad de Madrid      Madrid   
1  10  0.876310     920  12.183333              Galicia  Pontevedra   
2  36  1.194380     773  13.883333            Andalucía       Cádiz   
3  41  0.876310     773  15.333333  Comunidad de Madrid      Madrid   
4  42  0.876310     920  18.366667              Galicia   La Coruña   

                   HAB     SEX             EDAD                  EDUC  \
0       Más de 100.000   Mujer  De 50 a 64 años  Educación secundaria   
1       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
2       Más de 100.000  Hombre  De 65 a 79 años    Educación superior   
3       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
4  De 10.000 a 50.0000   Mujer  De 65 a 79 años   Primaria o inferior   

               COB                    LIVING       MARITAL HSIZE  \
0  Resto del mundo     Conviviendo en pareja      Casado/a     3   
1           España     Conviviendo en pareja      Casado/a     3   
2           España     Conviviendo en pareja      Casado/a     4   
3           España  No conviviendo en pareja       Viudo/a     1   
4           España  No conviviendo en pareja  Divorciado/a     1   

                                            ACTIVITY              FINANCIAL  \
0                                       Está en paro  Con cierta dificultad   
1  Cobra jubilación, prejubilación o pensión/inca...   Con cierta facilidad   
2  Cobra jubilación, prejubilación o pensión/inca...  Con cierta dificultad   
3  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   
4  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   

     NCHILD     PCHILD       EDUC_CHILDREN CONTACT_CHILDREN INT_USE  \
0         1  Sí, todos         No contesta   Todos los días      No   
1         3  Sí, todos  Educación superior   Todos los días      No   
2         3         No  Educación superior   Todos los días      Sí   
3  No tiene        NaN                 NaN              NaN      No   
4         2         No  Educación superior   Todos los días      No   

  INT_DEVICE_1 INT_DEVICE_2 INT_DEVICE_3 INT_DEVICE_95 INT_DEVICE_98  \
0          NaN          NaN          NaN           NaN           NaN   
1          NaN          NaN          NaN           NaN           NaN   
2           No           Sí           No            No            No   
3          NaN          NaN          NaN           NaN           NaN   
4          NaN          NaN          NaN           NaN           NaN   

  INT_DEVICE_99 INT_DEVICE_TEXT  INT_FREQ INT_LOCATION_1 INT_LOCATION_2  \
0           NaN               -       NaN            NaN            NaN   
1           NaN               -       NaN            NaN            NaN   
2            No               -  Cada día             Sí             No   
3           NaN               -       NaN            NaN            NaN   
4           NaN               -       NaN            NaN            NaN   

  INT_LOCATION_3 INT_LOCATION_95 INT_LOCATION_98 INT_LOCATION_99  \
0            NaN             NaN             NaN             NaN   
1            NaN             NaN             NaN             NaN   
2             No              No              No              No   
3            NaN             NaN             NaN             NaN   
4            NaN             NaN             NaN             NaN   

  INT_LOCATION_TEXT INT_MEDICAL3 INT_MEDICAL24  INT_MEDICAL2019  \
0                 -           No            No               No   
1                 -           No            No               No   
2                 -           Sí            Sí  Si regularmente   
3                 -           No            No               No   
4                 -           No            No               No   

  INT_MEDICAL_HELP INT_MEDICAL_WHO_1 INT_MEDICAL_WHO_2 INT_MEDICAL_WHO_3  \
0               No               NaN               NaN

In [4]:
data.shape

(2011, 89)

In [5]:
# Rename snakecase
data.columns = data.columns.str.lower().str.replace(" ", "_")
data.head()

id      pond  entrev   duracion                 ccaa        prov  \
0   3  0.801296     773  15.066667  Comunidad de Madrid      Madrid   
1  10  0.876310     920  12.183333              Galicia  Pontevedra   
2  36  1.194380     773  13.883333            Andalucía       Cádiz   
3  41  0.876310     773  15.333333  Comunidad de Madrid      Madrid   
4  42  0.876310     920  18.366667              Galicia   La Coruña   

                   hab     sex             edad                  educ  \
0       Más de 100.000   Mujer  De 50 a 64 años  Educación secundaria   
1       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
2       Más de 100.000  Hombre  De 65 a 79 años    Educación superior   
3       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
4  De 10.000 a 50.0000   Mujer  De 65 a 79 años   Primaria o inferior   

               cob                    living       marital hsize  \
0  Resto del mundo     Conviviendo en pareja      Casado/a     3   
1           España     Conviviendo en pareja      Casado/a     3   
2           España     Conviviendo en pareja      Casado/a     4   
3           España  No conviviendo en pareja       Viudo/a     1   
4           España  No conviviendo en pareja  Divorciado/a     1   

                                            activity              financial  \
0                                       Está en paro  Con cierta dificultad   
1  Cobra jubilación, prejubilación o pensión/inca...   Con cierta facilidad   
2  Cobra jubilación, prejubilación o pensión/inca...  Con cierta dificultad   
3  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   
4  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   

     nchild     pchild       educ_children contact_children int_use  \
0         1  Sí, todos         No contesta   Todos los días      No   
1         3  Sí, todos  Educación superior   Todos los días      No   
2         3         No  Educación superior   Todos los días      Sí   
3  No tiene        NaN                 NaN              NaN      No   
4         2         No  Educación superior   Todos los días      No   

  int_device_1 int_device_2 int_device_3 int_device_95 int_device_98  \
0          NaN          NaN          NaN           NaN           NaN   
1          NaN          NaN          NaN           NaN           NaN   
2           No           Sí           No            No            No   
3          NaN          NaN          NaN           NaN           NaN   
4          NaN          NaN          NaN           NaN           NaN   

  int_device_99 int_device_text  int_freq int_location_1 int_location_2  \
0           NaN               -       NaN            NaN            NaN   
1           NaN               -       NaN            NaN            NaN   
2            No               -  Cada día             Sí             No   
3           NaN               -       NaN            NaN            NaN   
4           NaN               -       NaN            NaN            NaN   

  int_location_3 int_location_95 int_location_98 int_location_99  \
0            NaN             NaN             NaN             NaN   
1            NaN             NaN             NaN             NaN   
2             No              No              No              No   
3            NaN             NaN             NaN             NaN   
4            NaN             NaN             NaN             NaN   

  int_location_text int_medical3 int_medical24  int_medical2019  \
0                 -           No            No               No   
1                 -           No            No               No   
2                 -           Sí            Sí  Si regularmente   
3                 -           No            No               No   
4                 -           No            No               No   

  int_medical_help int_medical_who_1 int_medical_who_2 int_medical_who_3  \
0               No               NaN               NaN

In [6]:
# Rename the columns spanish-english and with meaningfull names
data.columns = data.columns.str.replace("entrev", "interv")
data.columns = data.columns.str.replace("duracion", "duration")
data.columns = data.columns.str.replace("provincia", "province")
data.columns = data.columns.str.replace("hab", "res")
data.columns = data.columns.str.replace("edad", "age")
data.columns = data.columns.str.replace("cob", "locbirth")
data.columns = data.columns.str.replace("int_device_1", "int_pc")
data.columns = data.columns.str.replace("int_device_2", "int_mobile")
data.columns = data.columns.str.replace("int_device_3", "int_tablet")
data.columns = data.columns.str.replace("int_device_95", "int_otherdev")
data.columns = data.columns.str.replace("int_device_98", "int_devns")
data.columns = data.columns.str.replace("int_device_99", "int_devnc")
data.columns = data.columns.str.replace("int_location_1", "int_home")
data.columns = data.columns.str.replace("int_location_2", "int_work")
data.columns = data.columns.str.replace("int_location_3", "int_public")
data.columns = data.columns.str.replace("int_location_95", "int_otherpl")
data.columns = data.columns.str.replace("int_location_98", "int_plns")
data.columns = data.columns.str.replace("int_location_99", "int_plnc")
data.columns = data.columns.str.replace("srh", "general_health")
     

data.head()

id      pond  interv   duration                 ccaa        prov  \
0   3  0.801296     773  15.066667  Comunidad de Madrid      Madrid   
1  10  0.876310     920  12.183333              Galicia  Pontevedra   
2  36  1.194380     773  13.883333            Andalucía       Cádiz   
3  41  0.876310     773  15.333333  Comunidad de Madrid      Madrid   
4  42  0.876310     920  18.366667              Galicia   La Coruña   

                   res     sex              age                  educ  \
0       Más de 100.000   Mujer  De 50 a 64 años  Educación secundaria   
1       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
2       Más de 100.000  Hombre  De 65 a 79 años    Educación superior   
3       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
4  De 10.000 a 50.0000   Mujer  De 65 a 79 años   Primaria o inferior   

          locbirth                    living       marital hsize  \
0  Resto del mundo     Conviviendo en pareja      Casado/a     3   
1           España     Conviviendo en pareja      Casado/a     3   
2           España     Conviviendo en pareja      Casado/a     4   
3           España  No conviviendo en pareja       Viudo/a     1   
4           España  No conviviendo en pareja  Divorciado/a     1   

                                            activity              financial  \
0                                       Está en paro  Con cierta dificultad   
1  Cobra jubilación, prejubilación o pensión/inca...   Con cierta facilidad   
2  Cobra jubilación, prejubilación o pensión/inca...  Con cierta dificultad   
3  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   
4  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   

     nchild     pchild       educ_children contact_children int_use int_pc  \
0         1  Sí, todos         No contesta   Todos los días      No    NaN   
1         3  Sí, todos  Educación superior   Todos los días      No    NaN   
2         3         No  Educación superior   Todos los días      Sí     No   
3  No tiene        NaN                 NaN              NaN      No    NaN   
4         2         No  Educación superior   Todos los días      No    NaN   

  int_mobile int_tablet int_otherdev int_devns int_devnc int_device_text  \
0        NaN        NaN          NaN       NaN       NaN               -   
1        NaN        NaN          NaN       NaN       NaN               -   
2         Sí         No           No        No        No               -   
3        NaN        NaN          NaN       NaN       NaN               -   
4        NaN        NaN          NaN       NaN       NaN               -   

   int_freq int_home int_work int_public int_otherpl int_plns int_plnc  \
0       NaN      NaN      NaN        NaN         NaN      NaN      NaN   
1       NaN      NaN      NaN        NaN         NaN      NaN      NaN   
2  Cada día       Sí       No         No          No       No       No   
3       NaN      NaN      NaN        NaN         NaN      NaN      NaN   
4       NaN      NaN      NaN        NaN         NaN      NaN      NaN   

  int_location_text int_medical3 int_medical24  int_medical2019  \
0                 -           No            No               No   
1                 -           No            No               No   
2                 -           Sí            Sí  Si regularmente   
3                 -           No            No               No   
4                 -           No            No               No   

  int_medical_help int_medical_who_1 int_medical_who_2 int_medical_who_3  \
0               No               NaN               NaN               NaN   
1               No               NaN               NaN               NaN   
2               No               NaN               NaN               NaN   
3               No               NaN               NaN               NaN   
4  Si regularmente                No                Sí                No   

  int_medical_who_4 in

Legend for the HL questions
- HL1: Degree of Difficulty You Would Find in Performing the Following Activity: Finding Information About Treatments Associated with Diseases of Interest
- HL2: Degree of Difficulty You Would Find in Performing the Following Activity: Finding Out Where to Get Professional Help When You Are Sick (e.g., Doctor, Pharmacist, or Psychologist)
- HL3: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding What the Doctor Tells You
- HL4: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding the Instructions of the Doctor or Pharmacist on How to Take Prescribed Medicines
- HL5: Degree of Difficulty You Would Find in Performing the Following Activity: Assessing When You Might Need a Second Opinion from Another Doctor
- HL6: Degree of Difficulty You Would Find in Performing the Following Activity: Using the Information Provided by the Doctor to Make Decisions About Your Illness
- HL7: Degree of Difficulty You Would Find in Performing the Following Activity: Following the Instructions of Your Doctor or Pharmacist
- HL8: Degree of Difficulty You Would Find in Performing the Following Activity: Finding Information on How to Address Mental Health Problems, Such as Stress or Depression
- HL9: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding Health Warnings Related to Habits Such as Smoking, Little Physical Exercise, or Excessive Alcohol Consumption
- HL10: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding Why You Need Early Detection Tests for Diseases or Medical Check-ups (e.g., Mammography, Blood Sugar, and Blood Pressure Tests)
- HL11: Degree of Difficulty You Would Find in Performing the Following Activity: Assessing the Reliability of Health Risk Information in the Media (e.g., TV, Internet, or Other Media)
- HL12: Degree of Difficulty You Would Find in Performing the Following Activity: Deciding How to Protect Yourself from Diseases Based on Information Provided by the Media (e.g., Newspapers, Brochures, Internet, or Other Media)
- HL13: Degree of Difficulty You Would Find in Performing the Following Activity: Finding Activities that Are Good for Your Mental Well-being (e.g., Meditation, Exercise, Walks, Pilates, etc.)
- HL14: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding Health Advice Given by Family and Friends
- HL15: Degree of Difficulty You Would Find in Performing the Following Activity: Understanding Information Provided by the Media on How to Improve Your Health (e.g., Internet, Newspapers, Magazines)
- HL16: Degree of Difficulty You Would Find in Performing the Following Activity: Assessing Which of Your Daily Habits Affect Your Health (e.g., Habits Related to Alcohol Consumption, Eating Habits, Exercise, etc.)


In [7]:
# Null values
null_count = data.isnull().sum()
print(null_count)

id                        0
pond                      0
interv                    0
duration                  0
ccaa                      0
prov                      0
res                       0
sex                       0
age                       0
educ                      0
locbirth                  0
living                    0
marital                   0
hsize                     0
activity                  0
financial                 0
nchild                    0
pchild                  322
educ_children           322
contact_children        322
int_use                   0
int_pc                  365
int_mobile              365
int_tablet              365
int_otherdev            365
int_devns               365
int_devnc               365
int_device_text           0
int_freq                365
int_home                365
int_work                365
int_public              365
int_otherpl             365
int_plns                365
int_plnc                365
int_location_text   

In [8]:
# Drop irrelevant columns and/or with a large number of missing values
drop_list = ['int_device_text',
'int_location_text', 
'int_medical_who_1',      
'int_medical_who_2',      
'int_medical_who_3',      
'int_medical_who_4',      
'int_medical_who_95',     
'int_medical_who_98',     
'int_medical_who_99',     
'int_medical_who_txt',
'limit_type',
'limit4weeks',
'med_sup_who_1',          
'med_sup_who_2',          
'med_sup_who_3',          
'med_sup_who_4',          
'med_sup_who_95',         
'med_sup_who_99',         
'med_sup_who_text',
'int_location_text',
'int_devns',           
'int_devnc',
'int_plns',         
'int_plnc',
]
data = data.drop(drop_list, axis=1)
print(data.shape)
data.head()

(2011, 66)


id      pond  interv   duration                 ccaa        prov  \
0   3  0.801296     773  15.066667  Comunidad de Madrid      Madrid   
1  10  0.876310     920  12.183333              Galicia  Pontevedra   
2  36  1.194380     773  13.883333            Andalucía       Cádiz   
3  41  0.876310     773  15.333333  Comunidad de Madrid      Madrid   
4  42  0.876310     920  18.366667              Galicia   La Coruña   

                   res     sex              age                  educ  \
0       Más de 100.000   Mujer  De 50 a 64 años  Educación secundaria   
1       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
2       Más de 100.000  Hombre  De 65 a 79 años    Educación superior   
3       Más de 100.000   Mujer  De 65 a 79 años   Primaria o inferior   
4  De 10.000 a 50.0000   Mujer  De 65 a 79 años   Primaria o inferior   

          locbirth                    living       marital hsize  \
0  Resto del mundo     Conviviendo en pareja      Casado/a     3   
1           España     Conviviendo en pareja      Casado/a     3   
2           España     Conviviendo en pareja      Casado/a     4   
3           España  No conviviendo en pareja       Viudo/a     1   
4           España  No conviviendo en pareja  Divorciado/a     1   

                                            activity              financial  \
0                                       Está en paro  Con cierta dificultad   
1  Cobra jubilación, prejubilación o pensión/inca...   Con cierta facilidad   
2  Cobra jubilación, prejubilación o pensión/inca...  Con cierta dificultad   
3  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   
4  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   

     nchild     pchild       educ_children contact_children int_use int_pc  \
0         1  Sí, todos         No contesta   Todos los días      No    NaN   
1         3  Sí, todos  Educación superior   Todos los días      No    NaN   
2         3         No  Educación superior   Todos los días      Sí     No   
3  No tiene        NaN                 NaN              NaN      No    NaN   
4         2         No  Educación superior   Todos los días      No    NaN   

  int_mobile int_tablet int_otherdev  int_freq int_home int_work int_public  \
0        NaN        NaN          NaN       NaN      NaN      NaN        NaN   
1        NaN        NaN          NaN       NaN      NaN      NaN        NaN   
2         Sí         No           No  Cada día       Sí       No         No   
3        NaN        NaN          NaN       NaN      NaN      NaN        NaN   
4        NaN        NaN          NaN       NaN      NaN      NaN        NaN   

  int_otherpl int_medical3 int_medical24  int_medical2019 int_medical_help  \
0         NaN           No            No               No               No   
1         NaN           No            No               No               No   
2          No           Sí            Sí  Si regularmente               No   
3         NaN           No            No               No               No   
4         NaN           No            No               No  Si regularmente   

  general_health         chronic                limit      pain  \
0       Muy malo  Sí, más de uno             Limitado  Moderado   
1           Malo  Sí, más de uno          No limitado  Moderado   
2          Bueno              No          No limitado  Moderado   
3           Malo  Sí, más de uno             Limitado  Moderado   
4       Muy malo         Sí, uno  Gravemente limitado    Severo   

                     doctor         medical_exp hosp  \
0           Más de 12 meses  Entre 1 y 12 meses   No   
1  En las últimas 4 semanas     Más de 12 meses   No   
2        Entre 1 y 12 meses  Entre 1 y 12 meses   No   
3  En las últimas 4 semanas     Más de 12 meses   No   
4  En las últimas 4 semanas  Entre 1 y 12 meses   No   

                                    smoking        happy        loneliness  \
0  No fumo actualmente

In [9]:
# Checking uniqe values for the categorical variables with NaN to decide an strategy
cat_nan = ['pchild',                 
'educ_children',          
'contact_children',       
'int_pc',            
'int_mobile',            
'int_tablet',            
'int_otherdev',           
'int_freq',                
'int_home',          
'int_work',          
'int_public',          
'int_otherpl',             
] 

for column in cat_nan:
    print(f"\n{column}:\n{data[column].value_counts(dropna=False)}")



pchild:
No                   730
Sí, todos            621
Sí, pero no todos    338
NaN                  322
Name: pchild, dtype: int64

educ_children:
Educación superior             1153
Educación secundaria            390
NaN                             322
Primera etapa de secundaria     103
Primaria o inferior              25
No contesta                      18
Name: educ_children, dtype: int64

contact_children:
Todos los días                           1327
NaN                                       322
Varias veces a la semana                  231
Alrededor de una vez a la semana           71
Menos de una vez al mes                    19
Alrededor de una vez al mes                14
Alrededor de una vez cada dos semanas      13
Nunca                                       7
No contesta                                 4
No sabe                                     3
Name: contact_children, dtype: int64

int_pc:
Sí     1206
No      440
NaN     365
Name: int_pc, dtype: int64

int_mobil

In [10]:
# Handle categorical variables with mode
for column in cat_nan:
    # Replace NaN with the mode
    data[column].fillna(data[column].mode()[0], inplace=True)

In [11]:
# Null values
null_count = data.isnull().sum()
print(null_count)

id                  0
pond                0
interv              0
duration            0
ccaa                0
prov                0
res                 0
sex                 0
age                 0
educ                0
locbirth            0
living              0
marital             0
hsize               0
activity            0
financial           0
nchild              0
pchild              0
educ_children       0
contact_children    0
int_use             0
int_pc              0
int_mobile          0
int_tablet          0
int_otherdev        0
int_freq            0
int_home            0
int_work            0
int_public          0
int_otherpl         0
int_medical3        0
int_medical24       0
int_medical2019     0
int_medical_help    0
general_health      0
chronic             0
limit               0
pain                0
doctor              0
medical_exp         0
hosp                0
smoking             0
happy               0
loneliness          0
satisfaction        0
social_con

In [12]:
# Data types
data.dtypes

id                    int64
pond                float64
interv                int64
duration            float64
ccaa                 object
prov                 object
res                  object
sex                  object
age                  object
educ                 object
locbirth             object
living               object
marital              object
hsize                object
activity             object
financial            object
nchild               object
pchild               object
educ_children        object
contact_children     object
int_use              object
int_pc               object
int_mobile           object
int_tablet           object
int_otherdev         object
int_freq             object
int_home             object
int_work             object
int_public           object
int_otherpl          object
int_medical3         object
int_medical24        object
int_medical2019      object
int_medical_help     object
general_health       object
chronic             

In [13]:
# Numerical and categorical columns
num = data.select_dtypes(include=[np.number])
cat = data.select_dtypes(include=[object])

In [14]:
num.head()

id      pond  interv   duration
0   3  0.801296     773  15.066667
1  10  0.876310     920  12.183333
2  36  1.194380     773  13.883333
3  41  0.876310     773  15.333333
4  42  0.876310     920  18.366667

In [15]:
num.describe().T

count         mean          std        min          25%  \
id        2011.0  3811.798608  2609.324760   3.000000  1505.500000   
pond      2011.0     1.000000     0.281824   0.710793     0.790617   
interv    2011.0   842.014918   231.929286  18.000000   813.000000   
duration  2011.0    10.837742     3.329340   4.600000     8.433333   

                  50%          75%          max  
id        3352.000000  6051.500000  9472.000000  
pond         0.841610     1.194380     1.604841  
interv     975.000000   986.000000   992.000000  
duration    10.483333    12.658333    31.633333

In [16]:
print(cat.shape)
cat.head()

(2011, 62)


ccaa        prov                  res     sex  \
0  Comunidad de Madrid      Madrid       Más de 100.000   Mujer   
1              Galicia  Pontevedra       Más de 100.000   Mujer   
2            Andalucía       Cádiz       Más de 100.000  Hombre   
3  Comunidad de Madrid      Madrid       Más de 100.000   Mujer   
4              Galicia   La Coruña  De 10.000 a 50.0000   Mujer   

               age                  educ         locbirth  \
0  De 50 a 64 años  Educación secundaria  Resto del mundo   
1  De 65 a 79 años   Primaria o inferior           España   
2  De 65 a 79 años    Educación superior           España   
3  De 65 a 79 años   Primaria o inferior           España   
4  De 65 a 79 años   Primaria o inferior           España   

                     living       marital hsize  \
0     Conviviendo en pareja      Casado/a     3   
1     Conviviendo en pareja      Casado/a     3   
2     Conviviendo en pareja      Casado/a     4   
3  No conviviendo en pareja       Viudo/a     1   
4  No conviviendo en pareja  Divorciado/a     1   

                                            activity              financial  \
0                                       Está en paro  Con cierta dificultad   
1  Cobra jubilación, prejubilación o pensión/inca...   Con cierta facilidad   
2  Cobra jubilación, prejubilación o pensión/inca...  Con cierta dificultad   
3  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   
4  Cobra jubilación, prejubilación o pensión/inca...   Con mucha dificultad   

     nchild     pchild       educ_children contact_children int_use int_pc  \
0         1  Sí, todos         No contesta   Todos los días      No     Sí   
1         3  Sí, todos  Educación superior   Todos los días      No     Sí   
2         3         No  Educación superior   Todos los días      Sí     No   
3  No tiene         No  Educación superior   Todos los días      No     Sí   
4         2         No  Educación superior   Todos los días      No     Sí   

  int_mobile int_tablet int_otherdev  int_freq int_home int_work int_public  \
0         Sí         No           No  Cada día       Sí       No         No   
1         Sí         No           No  Cada día       Sí       No         No   
2         Sí         No           No  Cada día       Sí       No         No   
3         Sí         No           No  Cada día       Sí       No         No   
4         Sí         No           No  Cada día       Sí       No         No   

  int_otherpl int_medical3 int_medical24  int_medical2019 int_medical_help  \
0          No           No            No               No               No   
1          No           No            No               No               No   
2          No           Sí            Sí  Si regularmente               No   
3          No           No            No               No               No   
4          No           No            No               No  Si regularmente   

  general_health         chronic                limit      pain  \
0       Muy malo  Sí, más de uno             Limitado  Moderado   
1           Malo  Sí, más de uno          No limitado  Moderado   
2          Bueno              No          No limitado  Moderado   
3           Malo  Sí, más de uno             Limitado  Moderado   
4       Muy malo         Sí, uno  Gravemente limitado    Severo   

                     doctor         medical_exp hosp  \
0           Más de 12 meses  Entre 1 y 12 meses   No   
1  En las últimas 4 semanas     Más de 12 meses   No   
2        Entre 1 y 12 meses  Entre 1 y 12 meses   No   
3  En las últimas 4 semanas     Más de 12 meses   No   
4  En las últimas 4 semanas  Entre 1 y 12 meses   No   

                                    smoking        happy        loneliness  \
0  No fumo actualmente pero he fumado antes  No contesta             Nunca   
1   No fumo ni he fumado de manera habitual      Regular             Nunca   
2   No fumo ni he fumado de manera habitual      Regular    Ocasionalmente   
3

In [17]:
# Check unique values for categorical columns
counts = {}
for column in cat:
    counts[column] = cat[column].value_counts()
    print(f"\n{column}:\n{counts[column]}")



ccaa:
Andalucía              366
Cataluña               349
Comunidad de Madrid    270
Com. Valenciana        155
Galicia                129
País Vasco             106
Castilla y León        105
Canarias                99
Castilla la Mancha      72
Región de Murcia        65
Aragón                  62
Asturias                51
Extremadura             50
Illes Balears           46
Navarra                 35
Cantabria               31
La Rioja                20
Name: ccaa, dtype: int64

prov:
Barcelona      278
Madrid         202
Valencia       121
Sevilla        100
Cádiz           80
Murcia          65
Málaga          57
La Coruña       52
Las Palmas      52
Asturias        51
Pontevedra      49
Tenerife        47
Albacete        47
Balears         46
Guipúzcoa       46
Vizcaya         46
Zaragoza        43
Granada         42
Álava           41
Navarra         35
Gerona          32
Badajoz         32
Cantabria       31
Jaén            30
Valladolid      27
Córdoba         25
León    

### Approach for simplify categorical column and encoding
#### One-hot encoding when there is no inherent order or ranking among the categories (reat each category as a separate and independent feature) and ordinal encoding when there is a clear order or ranking among the categories


- I will combine "NS" (don't know) and "NC" (no answer) whenever they are separate                      

### Ordinal Encoding:
- 'res': Size of the Municipality of Residence
- 'sex': Gender (Binary)
- 'age': Age
- 'educ': Level of Education 
    Combine 'Primera etapa de secundaria' ('First stage of secondary school') and 'Educación secundaria' ('Secondary education'):      
- 'hsize': Household Size 
    Simplify into broader categories: 'Small:0', 'Medium:1', 'Large:2' (currently is a range 1-10).
- 'financial': Level of Financial Difficulty 
    Group 'Con cierta dificultad' with 'Con dificultad' and 'Con cierta facilidad' with 'Con facilidad'.
- 'nchild': Number of Children
    Group 3, 4, 5 in category '3 or more', and 6, 7, and 8 in '5 or more'.
- 'educ_children': Education Level of Children
    Combine 'Primera etapa de secundaria' ('First stage of secondary school') and 'Educación secundaria' ('Secondary education'):        
- 'contact_children': Contacts in the Last Twelve Months with Children 
    Use daily (Todos los días), weekly (Varias veces a la semana and Alrededor de una vez a la semana), monthly ('Alrededor de una vez al mes', 'Alrededor de una vez cada dos semanas' and 'Menos de una vez al mes') and never ('Nunca').
- 'int_freq': Frequency of Internet Use 
- 'int_medical2019': Internet Use for Medical Information in 2019 
- 'int_medical_help': Internet Use for Medical Help 
- 'chronic': Presence of Chronic or Long-Term Health Problems
- 'limit': Limitations Due to Health Issues 
- 'pain': Self-Reported Pain Level 
- 'doctor': Frequency of Visits to the Doctor 
- 'medical_exp': Time Since Last Specialist Consultation 
- 'smoking': Smoking Habits
- 'general_health': Self-Reported General Health
- 'happy': Self-Reported Happiness
- 'loneliness': Self-Reported Loneliness
- 'satisfaction': Life Satisfaction (TARGET)
- 'social_contact': Frequency of Social Contact 
    Use daily (Todos los días), weekly (Varias veces a la semana and Alrededor de una vez a la semana), monthly ('Alrededor de una vez al mes', 'Alrededor de una vez cada dos semanas' and 'Menos de una vez al mes') and never ('Nunca').
- 'social_family': Frequency of Social Contact with Family
    Use daily (Todos los días), weekly (Varias veces a la semana and Alrededor de una vez a la semana), monthly ('Alrededor de una vez al mes', 'Alrededor de una vez cada dos semanas' and 'Menos de una vez al mes') and never ('Nunca').
- 'social_perceived': Perceived Social Interaction 
- 'int_limitations': Internet Use Limitations 
    Combine 'Con dificultades, necessito ayuda' and 'Con dificultades, no puedo usar ordenador/telefono móbil'.
- 'med_sup': Use of Medical Support 
- 'hl'(all): Health Literacy 

### One-Hot Encoding:
- 'ccaa': Autonomous Community of Residence (Southern, Eastern, Central, Northern Spain grouping)
    Given the large number of categories, consider grouping them into broader regions for simplicity:
    - Southern Spain: Andalucía, Extremadura
    - Eastern Spain: Cataluña, Comunidad Valenciana
    - Central Spain: Comunidad de Madrid, Castilla y León, Castilla-La Mancha
    - Northern Spain: Galicia, País Vasco, Asturias, Cantabria, La Rioja, Navarra, Aragón.
- 'prov': Province of Residence (Grouping into regions or drop it)
- 'locbirth': Place of Birth 
    Combine all European countries in the category 'Europe'.
- 'living': Living Situation
- 'marital': Marital Status 
    Combine less frequency in 'Others'.
- 'activity': Relationship with Activity 
    Consider combining less frequent categories into a broader 'Other' category.
- 'pchild': Presence of Children 
- 'int_use' 
- 'int_pc' 
- 'int_mobile' 
- 'int_tablet'
- 'int_otherdev' 
- 'int_home'
- 'int_work'
- 'int_public'
- 'int_otherpl'
- 'int_medical3'
- 'int_medical24'
- 'hosp': Hospitalization in Last Months 










In [18]:
# Ordinal encoding and simplifying categories

In [19]:
def clean_res(x):
    if x == 'Menos de 10.000':
        return 0
    elif x == 'De 10.000 a 50.0000':
        return 0.33
    elif x == 'De 50.001 a 100.000':
        return 0.67
    else: 
        return 1

cat['res'] = cat['res'].map(clean_res)
cat['res'].value_counts()

1.00    733
0.33    511
0.00    400
0.67    367
Name: res, dtype: int64

In [20]:
cat['sex'].replace({"Mujer": 0, "Hombre": 1}, inplace=True)
cat['sex'].value_counts()

0    1072
1     939
Name: sex, dtype: int64

In [21]:
cat['age'].replace({"De 50 a 64 años":0, "De 65 a 79 años": 1}, inplace=True)
cat['age'].value_counts()

0    1247
1     764
Name: age, dtype: int64

In [22]:
cat['educ'].replace({"Primera etapa de secundaria": "Educación secundaria"}, inplace=True)

def clean_educ(x):
    if x in ['Educación superior' , 'No contesta']:
        return 1
    elif x in ['Educación secundaria']:
        return 0.5
    else:
        return 0  
cat['educ'] = cat['educ'].map(clean_educ) 


cat['educ'].value_counts()

0.5    1086
1.0     623
0.0     302
Name: educ, dtype: int64

In [23]:
def clean_hsize(x):
    if x in ['1', '2', '3']:
        return 0
    elif x in ['4', '5']:
        return 0.5
    else:
        return 1

cat['hsize'] = cat['hsize'].map(clean_hsize)
cat['hsize'].value_counts()
# I put the 'No contesta' values with the mode

0.0    1492
0.5     490
1.0      29
Name: hsize, dtype: int64

In [24]:
def clean_financial(x):
    if x in ['Con mucha dificultad']:
        return 0
    elif x in ['Con cierta dificultad', 'Con dificultad']:
        return 0.33
    elif x in ['Con facilidad', 'Con cierta facilidad', 'No contesta']:
        return 0.67
    else:
        return 1

cat['financial'] = cat['financial'].map(clean_financial)
cat['financial'].value_counts()
# I put the 'No contesta' values with the mode

0.67    1152
0.33     632
0.00     150
1.00      77
Name: financial, dtype: int64

In [25]:
def clean_nchild(x):
    if x in ['No tiene']:
        return 0 
    elif x in ['1', '2', '3', 'No contesta']:
        return 0.33
    elif x in ['3', '4']:
        return 0.67
    else:
        return 1

cat['nchild'] = cat['nchild'].map(clean_nchild)
cat['nchild'].value_counts()
# I put the 'No contesta' values with the mode

0.33    1631
0.00     315
0.67      47
1.00      18
Name: nchild, dtype: int64

In [26]:
cat['educ_children'].replace({"Primera etapa de secundaria": "Educación secundaria"}, inplace=True)


cat['educ_children'] = cat['educ_children'].map(clean_educ) 
cat['educ_children'].value_counts()

1.0    1493
0.5     493
0.0      25
Name: educ_children, dtype: int64

In [27]:
def clean_freq(x):
    if x in ['Todos los días','No contesta', 'No sabe']:
        return 1
    elif x in ['Varias veces a la semana', 'Alrededor de una vez a la semana']:
        return 0.67
    elif x in ['Alrededor de una vez cada dos semanas', 'Alrededor de una vez al mes', 'Menos de una vez al mes']:
        return 0.33
    else:
        return 0  
cat['contact_children'] = cat['contact_children'].map(clean_freq)
cat['contact_children'].value_counts()
# I put the 'No contesta' values with the mode

1.00    1656
0.67     302
0.33      46
0.00       7
Name: contact_children, dtype: int64

In [28]:
cat['int_freq'] = cat['int_freq'].map(clean_freq)
cat['int_freq'].value_counts()

0.00    1832
0.67     168
1.00       8
0.33       3
Name: int_freq, dtype: int64

In [29]:
def clean_freq2(x):
    if x == 'Si siempre':
        return 1.0
    elif x == 'Si regularmente':
        return 0.67
    elif x == 'Si ocasionalmente':
        return 0.33
    else:
        return 0.0 

cat['int_medical2019'] = cat['int_medical2019'].map(clean_freq2)
cat['int_medical2019'].value_counts()
# I put the 'No contesta' values with the mode

0.00    954
0.33    639
0.67    229
1.00    189
Name: int_medical2019, dtype: int64

In [30]:
cat['int_medical_help'] = cat['int_medical_help'].map(clean_freq2)
cat['int_medical_help'].value_counts()

0.00    1663
0.33     141
1.00     136
0.67      71
Name: int_medical_help, dtype: int64

In [31]:
def clean_general_health(x):
    if x == 'Muy malo':
        return 0.0
    elif x == 'Malo':
        return 0.25
    elif x == 'Regular':
        return 0.5
    elif x in ['Bueno','No sabe','No contesta']:
        return 0.75
    else:
        return 1.0

cat['general_health'] = cat['general_health'].map(clean_general_health)
cat['general_health'].value_counts()
# I put the 'No contesta' values with the mode

0.75    1058
0.50     561
1.00     224
0.25     113
0.00      55
Name: general_health, dtype: int64

In [32]:
def clean_chronic(x):
    if x == 'Sí, más de uno':
        return 0
    elif x == 'Sí, uno':
        return 0.5
    else:
        return 1  

cat['chronic'] = cat['chronic'].map(clean_chronic)
cat['chronic'].value_counts()
# I put the 'No contesta' values with the mode

1.0    1038
0.5     759
0.0     214
Name: chronic, dtype: int64

In [33]:
def clean_limit(x):
    if x == 'Gravemente limitado':
        return 0
    elif x == 'Limitado':
        return 0.5
    else:
        return 1

cat['limit'] = cat['limit'].map(clean_limit)
cat['limit'].value_counts()


1.0    1489
0.5     427
0.0      95
Name: limit, dtype: int64

In [34]:
def clean_pain(x):
    if x == 'Extremo':
        return 0
    elif x == 'Severo':
        return 0.2
    elif x == 'Moderado':
        return 0.4
    elif x == 'Leve':
        return 0.6
    elif x == 'Muy leve':
        return 0.8
    else:
        return 1

cat['pain'] = cat['pain'].map(clean_pain)
cat['pain'].value_counts()

1.0    979
0.4    383
0.6    367
0.2    166
0.8     82
0.0     34
Name: pain, dtype: int64

In [35]:
def clean_freq3(x):
    if x == 'Nunca':
        return 0.0
    elif x == 'Más de 12 meses':
        return 0.33
    elif x in ['Entre 1 y 12 meses','No sabe','No contesta']:
        return 0.67
    else:
        return 1  
    
cat['doctor'] = cat['doctor'].map(clean_freq3)
cat['doctor'].value_counts()
# I put the 'No contesta' values with the mode

0.67    861
1.00    703
0.33    416
0.00     31
Name: doctor, dtype: int64

In [36]:
cat['medical_exp'] = cat['medical_exp'].map(clean_freq3)
cat['medical_exp'].value_counts()

0.67    780
0.33    665
1.00    490
0.00     76
Name: medical_exp, dtype: int64

In [37]:
def clean_smoking(x):
    if x in ['No fumo ni he fumado de manera habitual','No sabe','No contesta']:
        return 1
    elif x in ['No fumo actualmente pero he fumado antes']:
        return 0.67
    elif x in ['Sí fumo, pero no a diario']:
        return 0.33
    else:
        return 0 

cat['smoking'] = cat['smoking'].map(clean_smoking)
cat['smoking'].value_counts()


1.00    891
0.67    762
0.00    318
0.33     40
Name: smoking, dtype: int64

In [38]:
def clean_loneliness(x):
    if x == 'A menudo/siempre':
        return 0.0
    elif x == 'Algunas veces':
        return 0.25
    elif x == 'Ocasionalmente':
        return 0.5
    elif x == 'Casi nunca':
        return 0.75
    else:
        return 1.0

cat['loneliness'] = cat['loneliness'].map(clean_loneliness)
cat['loneliness'].value_counts()
# I put the 'No contesta' values with the mode

1.00    939
0.75    533
0.25    223
0.50    205
0.00    111
Name: loneliness, dtype: int64

In [39]:
def clean_happy(x):
    if x == 'Muy infeliz':
        return 0.0
    elif x == 'Bastante Infeliz':
        return 0.25
    elif x == 'Regular':
        return 0.5
    elif x == 'Bastante feliz':
        return 0.75
    else:
        return 1.0

cat['happy'] = cat['happy'].map(clean_happy)
cat['happy'].value_counts()
# I put the 'No contesta' values with the mode

0.75    953
0.50    590
1.00    355
0.25     87
0.00     26
Name: happy, dtype: int64

In [40]:
def clean_freq4(x):
    if x in ['Cada día','No contesta', 'No sabe']:
        return 1
    elif x in ['Varias veces a la semana', 'Una vez a la semana']:
        return 0.75
    elif x in ['Varias veces al mes','Una vez al mes']:
        return 0.5
    elif x in ['Menos de una vez al mes']:
        return 0.25
    else:
        return 0  
    
cat['social_contact'] = cat['social_contact'].map(clean_freq4)
cat['social_contact'].value_counts()
# I put the 'No contesta' values with the mode

0.75    948
0.50    392
1.00    361
0.25    189
0.00    121
Name: social_contact, dtype: int64

In [41]:
cat['social_family'] = cat['social_family'].map(clean_freq4)
cat['social_family'].value_counts()

0.75    905
0.50    459
1.00    332
0.25    255
0.00     60
Name: social_family, dtype: int64

In [42]:
def clean_social_perceived(x):
    if x in ['Siempre','No contesta', 'No sabe']:
        return 1.0
    elif x == 'Normalmente':
        return 0.75
    elif x == 'A veces':
        return 0.5
    elif x == 'Rara vez':
        return 0.25
    else:
        return 0.0  
    
cat['social_perceived'] = cat['social_perceived'].map(clean_social_perceived)
cat['social_perceived'].value_counts()


1.00    892
0.75    441
0.50    275
0.00    258
0.25    145
Name: social_perceived, dtype: int64

In [43]:
def clean_int_limitations(x):
    if x in ['No, ninguna dificultad', 'No sabe']:
        return 1
    elif x == 'Alguna dificultad pero puedo usar móbiles/ordenadores de forma independiente':
        return 0.67
    elif x in ['Con dificultades, necessito ayuda', 'Con dificultades, no puedo usar ordenador/telefono móbil']:
        return 0.33
    else:
        return 0
    
cat['int_limitations'] = cat['int_limitations'].map(clean_int_limitations)
cat['int_limitations'].value_counts()


1.00    1742
0.67     222
0.33      39
0.00       8
Name: int_limitations, dtype: int64

In [44]:
def clean_med_sup(x):
    if x in ['No, nunca', 'No sabe', 'No contesta']:
        return 0
    elif x == 'Ocasionalmente':
        return 0.33
    elif x == 'Si, a menudo':
        return 0.67
    else:
        return 1
    
cat['med_sup'] = cat['med_sup'].map(clean_med_sup)
cat['med_sup'].value_counts()


0.00    1662
1.00     144
0.33     136
0.67      69
Name: med_sup, dtype: int64

In [45]:
def clean_hl(x):
    if x == 'Muy fácil':
        return 1
    elif x in ['Fácil','No sabe/No contesta']:
        return 0.67
    elif x == 'Difícil':
        return 0.33
    elif x == 'Muy difícil':
        return 0

In [46]:
hl = ['hl1', 'hl2', 'hl3', 'hl4', 'hl5', 'hl6', 'hl7', 'hl8', 'hl9', 'hl10', 'hl11', 'hl12', 'hl13', 'hl14', 'hl15', 'hl16']

for column in hl:
    cat[column] = cat[column].map(clean_hl)

# Check the value counts for some of the columns to verify
print(cat['hl1'].value_counts())
cat['hl10'].value_counts()

0.67    1579
0.33     202
1.00     192
0.00      38
Name: hl1, dtype: int64


0.67    1463
1.00     458
0.33      73
0.00      17
Name: hl10, dtype: int64

In [47]:
# Simplifying categories (for one-hot encoded)

In [48]:
def clean_ccaa(x):
    if x in ['Andalucía', 'Extremadura']:
        return 'southern'
    elif x in ['Cataluña', 'Com. Valenciana']:
        return 'eastern'
    elif x in ['Comunidad de Madrid', 'Castilla y León', 'Castilla-La Mancha']:
        return 'central'
    else:
        return 'northern'  
cat['ccaa'] = cat['ccaa'].map(clean_ccaa) 
cat['ccaa'].value_counts()

northern    716
eastern     504
southern    416
central     375
Name: ccaa, dtype: int64

In [49]:
def clean_locbirth(x):
    if x in ['España']:
        return 'España'
    elif x in ['Resto del mundo']:
        return 'Resto del mundo'
    else:
        return 'Europe'  
cat['locbirth'] = cat['locbirth'].map(clean_locbirth) 
cat['locbirth'].value_counts()

España             1940
Resto del mundo      53
Europe               18
Name: locbirth, dtype: int64

In [50]:
def clean_marital(x):
    if x in ['Casado/a']:
        return 'Casado/a'
    elif x in ['Soltero/a']:
        return 'Soltero/a'
    else:
        return 'Other'  
cat['marital'] = cat['marital'].map(clean_marital) 
cat['marital'].value_counts()

Casado/a     1483
Other         288
Soltero/a     240
Name: marital, dtype: int64

In [51]:
def clean_activity(x):
    if x in ['Cobra jubilación, prejubilación o pensión/incapacitación laboral']:
        return 'Cobra jubilación, prejubilación o pensión/incapacitación laboral'
    elif x in ['Trabaja por cuenta ajena']:
        return 'Trabaja por cuenta ajena'
    else:
        return 'Other'  
cat['activity'] = cat['activity'].map(clean_activity) 
cat['activity'].value_counts()

Cobra jubilación, prejubilación o pensión/incapacitación laboral    862
Trabaja por cuenta ajena                                            613
Other                                                               536
Name: activity, dtype: int64

In [52]:
cat.head()

ccaa        prov   res  sex  age  educ         locbirth  \
0   central      Madrid  1.00    0    0   0.5  Resto del mundo   
1  northern  Pontevedra  1.00    0    1   0.0           España   
2  southern       Cádiz  1.00    1    1   1.0           España   
3   central      Madrid  1.00    0    1   0.0           España   
4  northern   La Coruña  0.33    0    1   0.0           España   

                     living   marital  hsize  \
0     Conviviendo en pareja  Casado/a    0.0   
1     Conviviendo en pareja  Casado/a    0.0   
2     Conviviendo en pareja  Casado/a    0.5   
3  No conviviendo en pareja     Other    0.0   
4  No conviviendo en pareja     Other    0.0   

                                            activity  financial  nchild  \
0                                              Other       0.33    0.33   
1  Cobra jubilación, prejubilación o pensión/inca...       0.67    0.33   
2  Cobra jubilación, prejubilación o pensión/inca...       0.33    0.33   
3  Cobra jubilación, prejubilación o pensión/inca...       0.00    0.00   
4  Cobra jubilación, prejubilación o pensión/inca...       0.00    0.33   

      pchild  educ_children  contact_children int_use int_pc int_mobile  \
0  Sí, todos            1.0               1.0      No     Sí         Sí   
1  Sí, todos            1.0               1.0      No     Sí         Sí   
2         No            1.0               1.0      Sí     No         Sí   
3         No            1.0               1.0      No     Sí         Sí   
4         No            1.0               1.0      No     Sí         Sí   

  int_tablet int_otherdev  int_freq int_home int_work int_public int_otherpl  \
0         No           No       0.0       Sí       No         No          No   
1         No           No       0.0       Sí       No         No          No   
2         No           No       0.0       Sí       No         No          No   
3         No           No       0.0       Sí       No         No          No   
4         No           No       0.0       Sí       No         No          No   

  int_medical3 int_medical24  int_medical2019  int_medical_help  \
0           No            No             0.00              0.00   
1           No            No             0.00              0.00   
2           Sí            Sí             0.67              0.00   
3           No            No             0.00              0.00   
4           No            No             0.00              0.67   

   general_health  chronic  limit  pain  doctor  medical_exp hosp  smoking  \
0            0.00      0.0    0.5   0.4    0.33         0.67   No     0.67   
1            0.25      0.0    1.0   0.4    1.00         0.33   No     1.00   
2            0.75      1.0    1.0   0.4    0.67         0.67   No     1.00   
3            0.25      0.0    0.5   0.4    1.00         0.33   No     1.00   
4            0.00      0.5    0.0   0.2    1.00         0.67   No     1.00   

   happy  loneliness         satisfaction  social_contact  social_family  \
0    1.0        1.00          No contesta            0.00           0.50   
1    0.5        1.00              Regular            0.50           1.00   
2    0.5        0.50              Regular            0.50           0.50   
3    0.0        0.00              Regular            1.00           0.25   
4    0.5        0.75  Bastante satisfecho            0.75           0.75   

   social_perceived  int_limitations  med_sup   hl1   hl2   hl3   hl4   hl5  \
0               1.0             1.00     0.00  0.67  0.67  0.67  0.67  0.67   
1               1.0             1.00     0.00  0.67  0.67  0.67  0.67  0.67   
2               0.5             1.00     0.33  0.67  0.00  0.67  0.67  0.33   
3               0.0             1.00     0.00  0.67  0.33  0.00  1.00  0.67   
4               1.0             0.67     1.00  0.00  0.00  0.67  0.33  0.67   

    hl6   hl7   hl8   hl9  hl10  hl11  hl12  hl13  hl14  hl15  hl16  
0  0.67  0.67  0.67  1.00  0.67  0.67  0.67  0.67  0.67  0.67  0

In [53]:
# Check unique values for categorical columns
counts = {}
for column in cat:
    counts[column] = cat[column].value_counts()
    print(f"\n{column}:\n{counts[column]}")


ccaa:
northern    716
eastern     504
southern    416
central     375
Name: ccaa, dtype: int64

prov:
Barcelona      278
Madrid         202
Valencia       121
Sevilla        100
Cádiz           80
Murcia          65
Málaga          57
La Coruña       52
Las Palmas      52
Asturias        51
Pontevedra      49
Tenerife        47
Albacete        47
Balears         46
Guipúzcoa       46
Vizcaya         46
Zaragoza        43
Granada         42
Álava           41
Navarra         35
Gerona          32
Badajoz         32
Cantabria       31
Jaén            30
Valladolid      27
Córdoba         25
León            24
Almería         24
Tarragona       24
Toledo          22
Salamanca       21
Alicante        21
La Rioja        20
Ciudad Real     19
Cáceres         18
Lugo            16
Lérida          15
Guadalajara     15
Castellón       13
Ourense         12
Huesca          11
Cuenca          10
Segovia         10
Teruel           8
Burgos           8
Huelva           8
Palencia         5
Sori

In [54]:
# Concatenate numerical and categorical 
full_data = pd.concat([num,cat],axis = 1)
display(full_data.head())
full_data.shape

id      pond  interv   duration      ccaa        prov   res  sex  age  \
0   3  0.801296     773  15.066667   central      Madrid  1.00    0    0   
1  10  0.876310     920  12.183333  northern  Pontevedra  1.00    0    1   
2  36  1.194380     773  13.883333  southern       Cádiz  1.00    1    1   
3  41  0.876310     773  15.333333   central      Madrid  1.00    0    1   
4  42  0.876310     920  18.366667  northern   La Coruña  0.33    0    1   

   educ         locbirth                    living   marital  hsize  \
0   0.5  Resto del mundo     Conviviendo en pareja  Casado/a    0.0   
1   0.0           España     Conviviendo en pareja  Casado/a    0.0   
2   1.0           España     Conviviendo en pareja  Casado/a    0.5   
3   0.0           España  No conviviendo en pareja     Other    0.0   
4   0.0           España  No conviviendo en pareja     Other    0.0   

                                            activity  financial  nchild  \
0                                              Other       0.33    0.33   
1  Cobra jubilación, prejubilación o pensión/inca...       0.67    0.33   
2  Cobra jubilación, prejubilación o pensión/inca...       0.33    0.33   
3  Cobra jubilación, prejubilación o pensión/inca...       0.00    0.00   
4  Cobra jubilación, prejubilación o pensión/inca...       0.00    0.33   

      pchild  educ_children  contact_children int_use int_pc int_mobile  \
0  Sí, todos            1.0               1.0      No     Sí         Sí   
1  Sí, todos            1.0               1.0      No     Sí         Sí   
2         No            1.0               1.0      Sí     No         Sí   
3         No            1.0               1.0      No     Sí         Sí   
4         No            1.0               1.0      No     Sí         Sí   

  int_tablet int_otherdev  int_freq int_home int_work int_public int_otherpl  \
0         No           No       0.0       Sí       No         No          No   
1         No           No       0.0       Sí       No         No          No   
2         No           No       0.0       Sí       No         No          No   
3         No           No       0.0       Sí       No         No          No   
4         No           No       0.0       Sí       No         No          No   

  int_medical3 int_medical24  int_medical2019  int_medical_help  \
0           No            No             0.00              0.00   
1           No            No             0.00              0.00   
2           Sí            Sí             0.67              0.00   
3           No            No             0.00              0.00   
4           No            No             0.00              0.67   

   general_health  chronic  limit  pain  doctor  medical_exp hosp  smoking  \
0            0.00      0.0    0.5   0.4    0.33         0.67   No     0.67   
1            0.25      0.0    1.0   0.4    1.00         0.33   No     1.00   
2            0.75      1.0    1.0   0.4    0.67         0.67   No     1.00   
3            0.25      0.0    0.5   0.4    1.00         0.33   No     1.00   
4            0.00      0.5    0.0   0.2    1.00         0.67   No     1.00   

   happy  loneliness         satisfaction  social_contact  social_family  \
0    1.0        1.00          No contesta            0.00           0.50   
1    0.5        1.00              Regular            0.50           1.00   
2    0.5        0.50              Regular            0.50           0.50   
3    0.0        0.00              Regular            1.00           0.25   
4    0.5        0.75  Bastante satisfecho            0.75           0.75   

   social_perceived  int_limitations  med_sup   hl1   hl2   hl3   hl4   hl5  \
0               1.0             1.00     0.00  0.67  0.67  0.67  0.67  0.67   
1               1.0             1.00     0.00  0.67  0.67  0.67  0.67  0.67   
2               0.5             1.00     0.33  0.67  0.00  0.67  0.67  0.33   
3               0.0             1.00     0.00  0.67  0.33  0.00  1.00  0.67   
4           

(2011, 66)

In [55]:
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')

In [56]:
# X/y split (feature/target): X, y
y = full_data['satisfaction']
X = full_data.drop(['satisfaction', 'id', 'pond', 'interv', 'duration'], axis=1)
# I exclude some columns as predictors because they don't contribute to explaining the target variable

In [57]:
y.head()

0            No contesta
1                Regular
2                Regular
3                Regular
4    Bastante satisfecho
Name: satisfaction, dtype: object

In [58]:
X.head()

ccaa        prov   res  sex  age  educ         locbirth  \
0   central      Madrid  1.00    0    0   0.5  Resto del mundo   
1  northern  Pontevedra  1.00    0    1   0.0           España   
2  southern       Cádiz  1.00    1    1   1.0           España   
3   central      Madrid  1.00    0    1   0.0           España   
4  northern   La Coruña  0.33    0    1   0.0           España   

                     living   marital  hsize  ...   hl7   hl8   hl9  hl10  \
0     Conviviendo en pareja  Casado/a    0.0  ...  0.67  0.67  1.00  0.67   
1     Conviviendo en pareja  Casado/a    0.0  ...  0.67  0.67  0.67  0.67   
2     Conviviendo en pareja  Casado/a    0.5  ...  0.67  0.33  0.33  1.00   
3  No conviviendo en pareja     Other    0.0  ...  0.67  0.67  0.67  0.67   
4  No conviviendo en pareja     Other    0.0  ...  0.67  0.67  0.67  0.67   

   hl11  hl12  hl13  hl14  hl15  hl16  
0  0.67  0.67  0.67  0.67  0.67  0.67  
1  0.67  0.67  0.67  0.67  0.67  0.67  
2  0.00  0.33  0.33  0.67  0.33  0.67  
3  0.33  0.33  1.00  0.67  0.67  0.67  
4  0.67  0.33  0.33  0.67  0.67  0.67  

[5 rows x 61 columns]

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [60]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape) 

(1407, 61)

(604, 61)

(1407,)

(604,)

In [61]:
X_train_cat = X_train.select_dtypes(include = object)
X_train_num =X_train.select_dtypes(include = np.number)
X_test_cat = X_test.select_dtypes(include = object)
X_test_num =X_test.select_dtypes(include = np.number)

#### Scaling train and test

In [62]:
transformer = MinMaxScaler().fit(X_train_num)
X_train_num_norm = transformer.transform(X_train_num)
print(X_train_num_norm.shape)
X_train_num_scale = pd.DataFrame(X_train_num_norm, index = X_train_num.index, columns=X_train_num.columns)
X_train_num_scale.reset_index(drop = True, inplace = True)
X_train_num_scale.head()

(1407, 42)


res  sex  age  educ  hsize  financial  nchild  educ_children  \
0  1.00  0.0  0.0   0.5    0.0       0.33    0.00            1.0   
1  1.00  1.0  1.0   0.5    0.0       0.67    0.33            1.0   
2  0.33  1.0  0.0   0.5    0.0       0.67    0.00            1.0   
3  1.00  1.0  1.0   0.5    0.0       0.33    0.67            1.0   
4  0.67  0.0  0.0   0.5    0.0       0.67    0.33            0.5   

   contact_children  int_freq  ...   hl7   hl8   hl9  hl10  hl11  hl12  hl13  \
0              1.00       0.0  ...  0.67  0.33  0.67  0.67  0.67  0.67  0.67   
1              0.33       0.0  ...  0.67  0.67  0.67  0.67  0.67  0.67  0.67   
2              1.00       0.0  ...  0.67  0.67  0.67  0.67  0.67  0.67  0.67   
3              1.00       0.0  ...  0.67  0.33  0.67  0.67  0.00  0.33  0.67   
4              1.00       0.0  ...  0.67  0.33  0.67  0.67  0.67  0.67  0.33   

   hl14  hl15  hl16  
0  0.67  0.67  0.67  
1  0.67  0.67  0.67  
2  0.67  0.67  0.67  
3  0.33  0.00  0.67  
4  0.67  0.67  0.67  

[5 rows x 42 columns]

In [63]:
X_test_num_norm = transformer.transform(X_test_num)
print(X_test_num_norm.shape)
X_test_num_scale = pd.DataFrame(X_test_num_norm, index = X_test_num.index, columns=X_test_num.columns)
X_test_num_scale.reset_index(drop = True, inplace=True)
X_test_num_scale.head()

(604, 42)


res  sex  age  educ  hsize  financial  nchild  educ_children  \
0  0.33  1.0  0.0   1.0    0.0       0.67    0.00            1.0   
1  0.33  0.0  0.0   0.5    0.0       0.33    0.33            1.0   
2  1.00  0.0  0.0   0.0    0.0       0.67    0.33            1.0   
3  0.67  0.0  0.0   1.0    0.5       0.67    0.33            0.5   
4  0.00  1.0  0.0   1.0    0.0       1.00    0.00            1.0   

   contact_children  int_freq  ...   hl7   hl8   hl9  hl10  hl11  hl12  hl13  \
0               1.0      0.00  ...  1.00  0.67  1.00  1.00  0.67  1.00  0.67   
1               1.0      0.67  ...  0.67  0.67  0.67  0.67  0.67  0.67  0.67   
2               1.0      0.00  ...  0.67  0.67  0.33  0.67  0.67  0.67  0.67   
3               1.0      0.00  ...  0.67  0.67  1.00  1.00  0.33  0.33  0.67   
4               1.0      0.00  ...  0.67  0.67  0.67  0.67  0.67  0.67  0.67   

   hl14  hl15  hl16  
0  0.67  0.67  1.00  
1  0.67  0.67  0.67  
2  0.67  0.67  0.67  
3  0.33  0.00  1.00  
4  0.67  0.67  0.67  

[5 rows x 42 columns]

#### Encoding train and test

In [64]:
encoder = OneHotEncoder(drop='first').fit(X_train_cat)

cols = encoder.get_feature_names(input_features=X_train_cat.columns)

X_train_cat_encode = pd.DataFrame(encoder.transform(X_train_cat).toarray(),columns=cols)

X_train_cat_encode.reset_index(drop = True, inplace = True)
display(X_train_cat_encode.head())
X_train_cat_encode.shape

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ccaa_eastern  ccaa_northern  ccaa_southern  prov_Alicante  prov_Almería  \
0           0.0            1.0            0.0            0.0           0.0   
1           0.0            1.0            0.0            0.0           0.0   
2           0.0            1.0            0.0            0.0           0.0   
3           0.0            0.0            1.0            0.0           0.0   
4           1.0            0.0            0.0            0.0           0.0   

   prov_Asturias  prov_Badajoz  prov_Balears  prov_Barcelona  prov_Burgos  \
0            0.0           0.0           0.0             0.0          0.0   
1            0.0           0.0           0.0             0.0          0.0   
2            0.0           0.0           1.0             0.0          0.0   
3            0.0           0.0           0.0             0.0          0.0   
4            0.0           0.0           0.0             1.0          0.0   

   ...  int_mobile_Sí  int_tablet_Sí  int_otherdev_Sí  int_home_Sí  \
0  ...            1.0            0.0              0.0          1.0   
1  ...            1.0            0.0              0.0          1.0   
2  ...            0.0            0.0              0.0          1.0   
3  ...            1.0            1.0              0.0          1.0   
4  ...            1.0            0.0              0.0          1.0   

   int_work_Sí  int_public_Sí  int_otherpl_Sí  int_medical3_Sí  \
0          1.0            0.0             0.0              0.0   
1          0.0            1.0             0.0              1.0   
2          1.0            0.0             0.0              1.0   
3          0.0            1.0             0.0              1.0   
4          0.0            0.0             0.0              0.0   

   int_medical24_Sí  hosp_Sí  
0               0.0      0.0  
1               1.0      0.0  
2               1.0      0.0  
3               1.0      1.0  
4               0.0      0.0  

[5 rows x 74 columns]

(1407, 74)

In [65]:
cols = encoder.get_feature_names(input_features=X_test_cat.columns)

X_test_cat_encode = pd.DataFrame(encoder.transform(X_test_cat).toarray(),columns=cols)

X_test_cat_encode.reset_index(drop = True, inplace = True)
display(X_test_cat_encode.head())
X_test_cat_encode.shape


C:\Users\laiag\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ccaa_eastern  ccaa_northern  ccaa_southern  prov_Alicante  prov_Almería  \
0           0.0            1.0            0.0            0.0           0.0   
1           0.0            0.0            1.0            0.0           0.0   
2           0.0            1.0            0.0            0.0           0.0   
3           1.0            0.0            0.0            0.0           0.0   
4           0.0            1.0            0.0            0.0           0.0   

   prov_Asturias  prov_Badajoz  prov_Balears  prov_Barcelona  prov_Burgos  \
0            0.0           0.0           0.0             0.0          0.0   
1            0.0           0.0           0.0             0.0          0.0   
2            0.0           0.0           0.0             0.0          0.0   
3            0.0           0.0           0.0             1.0          0.0   
4            1.0           0.0           0.0             0.0          0.0   

   ...  int_mobile_Sí  int_tablet_Sí  int_otherdev_Sí  int_home_Sí  \
0  ...            1.0            0.0              0.0          1.0   
1  ...            1.0            0.0              0.0          1.0   
2  ...            1.0            0.0              0.0          1.0   
3  ...            1.0            0.0              0.0          1.0   
4  ...            1.0            0.0              0.0          1.0   

   int_work_Sí  int_public_Sí  int_otherpl_Sí  int_medical3_Sí  \
0          1.0            0.0             0.0              0.0   
1          1.0            0.0             0.0              1.0   
2          0.0            0.0             0.0              0.0   
3          1.0            1.0             0.0              0.0   
4          0.0            0.0             0.0              1.0   

   int_medical24_Sí  hosp_Sí  
0               0.0      0.0  
1               1.0      0.0  
2               0.0      0.0  
3               1.0      0.0  
4               1.0      0.0  

[5 rows x 74 columns]

(604, 74)

In [66]:
# Resetting indexes 
X_train_num_scale.reset_index(drop=True, inplace=True)  # Add inplace=True
X_test_num_scale.reset_index(drop=True, inplace=True)

X_train_cat_encode.reset_index(drop=True, inplace=True)
X_test_cat_encode.reset_index(drop=True, inplace=True)


In [67]:
# build X_train and X_test
X_train_processed = np.concatenate([X_train_num_scale, X_train_cat_encode], axis=1)
X_test_processed = np.concatenate([X_test_num_scale, X_test_cat_encode], axis=1)
print(X_train_processed.shape)
X_test_processed.shape

(1407, 116)


(604, 116)

In [68]:
# verify that dummies columns are in the same order and that the same column was dropped
list(zip(list(X_train_cat.columns),list(X_test_cat.columns)))
list(X_train_cat.columns)==list(X_test_cat.columns)

True

### Modeling and validations

In [69]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

# Create a list of classifiers
modelist = [
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
    # Add more classifiers as needed
]

In [70]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def model_test_classification(modellist):
    
    for model in modellist:
        
        model.fit(X_train_processed, y_train)
        
        # Training Data
        train_predictions = model.predict(X_train_processed)
        # Accuracy
        train_accuracy = round(accuracy_score(y_train, train_predictions), 2)
        # Classification Report
        train_classification_report = classification_report(y_train, train_predictions)
        # Confusion Matrix
        train_confusion_matrix = confusion_matrix(y_train, train_predictions)
        
        # Test Data
        test_predictions = model.predict(X_test_processed)
        # Accuracy
        test_accuracy = round(accuracy_score(y_test, test_predictions), 2)
        # Classification Report
        test_classification_report = classification_report(y_test, test_predictions)
        # Confusion Matrix
        test_confusion_matrix = confusion_matrix(y_test, test_predictions)
        
        display(model)
        display(pd.DataFrame({'ValType': ['Train', 'Test'], 'Accuracy': [train_accuracy, test_accuracy]}))
        print("Training Classification Report:\n", train_classification_report)
        print("Training Confusion Matrix:\n", train_confusion_matrix)
        print("\nTesting Classification Report:\n", test_classification_report)
        print("Testing Confusion Matrix:\n", test_confusion_matrix)

In [71]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [72]:
%%time
model_test_classification(modelist)

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


RandomForestClassifier()

ValType  Accuracy
0   Train      1.00
1    Test      0.57

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       1.00      1.00      1.00        53
  Bastante satisfecho       1.00      1.00      1.00       758
     Muy insatisfecho       1.00      1.00      1.00        15
       Muy satisfecho       1.00      1.00      1.00       257
          No contesta       1.00      1.00      1.00        17
              No sabe       1.00      1.00      1.00         7
              Regular       1.00      1.00      1.00       300

             accuracy                           1.00      1407
            macro avg       1.00      1.00      1.00      1407
         weighted avg       1.00      1.00      1.00      1407

Training Confusion Matrix:
 [[ 53   0   0   0   0   0   0]
 [  0 758   0   0   0   0   0]
 [  0   0  15   0   0   0   0]
 [  0   0   0 257   0   0   0]
 [  0   0   0   0  17   0   0]
 [  0   0   0   0   0   7   0]
 [  0   0   0   0   0   0 300]]

Testing Classification R

GradientBoostingClassifier()

ValType  Accuracy
0   Train      0.86
1    Test      0.56

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       1.00      0.94      0.97        53
  Bastante satisfecho       0.83      0.95      0.89       758
     Muy insatisfecho       1.00      1.00      1.00        15
       Muy satisfecho       0.90      0.67      0.77       257
          No contesta       1.00      1.00      1.00        17
              No sabe       1.00      1.00      1.00         7
              Regular       0.89      0.77      0.83       300

             accuracy                           0.86      1407
            macro avg       0.95      0.91      0.92      1407
         weighted avg       0.87      0.86      0.86      1407

Training Confusion Matrix:
 [[ 50   3   0   0   0   0   0]
 [  0 721   0  15   0   0  22]
 [  0   0  15   0   0   0   0]
 [  0  78   0 172   0   0   7]
 [  0   0   0   0  17   0   0]
 [  0   0   0   0   0   7   0]
 [  0  63   0   5   0   0 232]]

Testing Classification R

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

LogisticRegression()

ValType  Accuracy
0   Train      0.67
1    Test      0.55

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       0.72      0.34      0.46        53
  Bastante satisfecho       0.66      0.91      0.77       758
     Muy insatisfecho       1.00      0.20      0.33        15
       Muy satisfecho       0.72      0.34      0.46       257
          No contesta       0.00      0.00      0.00        17
              No sabe       1.00      0.14      0.25         7
              Regular       0.63      0.46      0.53       300

             accuracy                           0.67      1407
            macro avg       0.68      0.34      0.40      1407
         weighted avg       0.67      0.67      0.63      1407

Training Confusion Matrix:
 [[ 18  15   0   0   0   0  20]
 [  1 691   0  25   0   0  41]
 [  2   2   3   0   0   0   8]
 [  0 162   0  88   0   0   7]
 [  0  13   0   2   0   0   2]
 [  1   3   0   1   0   1   1]
 [  3 154   0   6   0   0 137]]

Testing Classification R

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metr

SVC()

ValType  Accuracy
0   Train      0.59
1    Test      0.53

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       0.00      0.00      0.00        53
  Bastante satisfecho       0.59      0.99      0.74       758
     Muy insatisfecho       0.00      0.00      0.00        15
       Muy satisfecho       0.00      0.00      0.00       257
          No contesta       0.00      0.00      0.00        17
              No sabe       0.00      0.00      0.00         7
              Regular       0.66      0.29      0.40       300

             accuracy                           0.59      1407
            macro avg       0.18      0.18      0.16      1407
         weighted avg       0.46      0.59      0.48      1407

Training Confusion Matrix:
 [[  0  31   0   0   0   0  22]
 [  0 751   0   0   0   0   7]
 [  0   5   0   0   0   0  10]
 [  0 254   0   0   0   0   3]
 [  0  16   0   0   0   0   1]
 [  0   5   0   0   0   0   2]
 [  0 214   0   0   0   0  86]]

Testing Classification R

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-d

KNeighborsClassifier()

ValType  Accuracy
0   Train       0.6
1    Test       0.5

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       0.38      0.06      0.10        53
  Bastante satisfecho       0.60      0.93      0.73       758
     Muy insatisfecho       1.00      0.07      0.12        15
       Muy satisfecho       0.52      0.25      0.34       257
          No contesta       0.00      0.00      0.00        17
              No sabe       0.00      0.00      0.00         7
              Regular       0.66      0.24      0.35       300

             accuracy                           0.60      1407
            macro avg       0.45      0.22      0.23      1407
         weighted avg       0.59      0.60      0.54      1407

Training Confusion Matrix:
 [[  3  39   0   4   0   0   7]
 [  3 703   0  33   0   0  19]
 [  0   9   1   0   0   0   5]
 [  1 188   0  65   0   0   3]
 [  0  13   0   2   0   0   2]
 [  0   7   0   0   0   0   0]
 [  1 208   0  20   0   0  71]]

Testing Classification R

C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\laiag\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DecisionTreeClassifier()

ValType  Accuracy
0   Train      1.00
1    Test      0.51

Training Classification Report:
                        precision    recall  f1-score   support

Bastante insatisfecho       1.00      1.00      1.00        53
  Bastante satisfecho       1.00      1.00      1.00       758
     Muy insatisfecho       1.00      1.00      1.00        15
       Muy satisfecho       1.00      1.00      1.00       257
          No contesta       1.00      1.00      1.00        17
              No sabe       1.00      1.00      1.00         7
              Regular       1.00      1.00      1.00       300

             accuracy                           1.00      1407
            macro avg       1.00      1.00      1.00      1407
         weighted avg       1.00      1.00      1.00      1407

Training Confusion Matrix:
 [[ 53   0   0   0   0   0   0]
 [  0 758   0   0   0   0   0]
 [  0   0  15   0   0   0   0]
 [  0   0   0 257   0   0   0]
 [  0   0   0   0  17   0   0]
 [  0   0   0   0   0   7   0]
 [  0   0   0   0   0   0 300]]

Testing Classification R

It's important to note that the decision tree model has a perfect training accuracy, which may indicate overfitting. However, its testing accuracy is relatively lower compared to the training accuracy, suggesting that the model may not generalize well to unseen data.

The Random Forest Classifier seems to have high training accuracy but a lower testing accuracy, which might be a sign of overfitting as well.

The Gradient Boosting Classifier has a decent training accuracy but struggles to generalize to the testing data.

The Logistic Regression model has a relatively balanced performance on both training and testing data.

The Support Vector Classifier and K-Nearest Neighbors models seem to struggle with generalization.

Some conclusions: In summary, while the training accuracy is high for some models, the testing accuracy indicates that there might be room for improvement, and the models may need tuning or different approaches to enhance their performance on unseen data.